### ISSUE TITLE
configure CORS in otp

### ISSUE THREAD

**Issue by stemove** [openmove/odh-mentor-otp#33]
- [ ] investigate to add cors headers in otp response to able access from other domains

- [ ] espose it trought ENV var

**Comment by zabuTNT** [comment]
It is not a problem of OTP because otp accept all:
https://github.com/opentripplanner/OpenTripPlanner/blob/a499a4f2f3529c53a7859a985b7c1a61033b71dc/src/main/java/org/opentripplanner/standalone/server/CorsFilter.java

I think that the problem is on the hosting machine, maybe there is a proxy in between that rewrite the headers?

I have not problem with this:
https://journey.opendatahub.testingmachine.eu/
